# 路由信息Request


# 初始化路由信息表
GET http://{{host}}:{{port}}/{{path}}/route/init
Content-Type: application/json

###  获得所有路由信息
POST  http://{{host}}:{{port}}/{{path}}/route/all
Content-Type: application/json

{
"page":1,
"limit":10
}

### 新增路由信息
POST http://{{host}}:{{port}}/route
Content-Type: application/json

{

  "routeId": "cloud-uum",
  "uri": "lb://CLOUD-UUM",
  "predicates": [{
    "name": "Path",
    "args": {
      "pattern": "/uum/**"
    }
  }],
  "filters": [{
      "name": "RewritePath",
      "args": {
        "regexp": "/uum/(?<remaining>.*)",
        "replacement": "/${remaining}"
      }
  }],
  "orders": 1,
  "description": "统一用户服务",
  "status": 1
}

### 修改网关状态
PUT http://{{host}}:{{port}}/route/status/7970242716962177025?status=1
Content-Type: application/json



###

